### PR TITLE
fixed npm dependency issues

### PR DESCRIPTION
**Pull request by GitMensch**
I don't feel comfortable in merging this myself as I only have a clue about npm and don't know if this will break anything or not. It _seemed_ to still work as expected and `npm audit` shows no warnings any more...

### CODE REVIEW

**Comment by DrMerfy** [comment]
Hi, thanks for this!

A couple of questions:
1. Is it breaking on vscode 1.0.0? 
2. How do we use minimist?

**Comment by GitMensch** [comment]
I honestly have no clue :-) If I remember correctly minimist is pulled in via the vscode dependency.
You may run `npm audit` and have a look - that's a local run on the feature branch:

~~~
> npm i --package-lock-only
> npm audit                

                       === npm audit security report ===                        

# Run  npm install --save-dev tslint@5.20.1  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Dependency of   tslint [dev]                                                  

  Path            tslint > optimist > minimist                                  

  More info       https://npmjs.com/advisories/1179                             




  High            Prototype Pollution                                           

  Package         dot-prop                                                      

  Dependency of   tslint [dev]                                                  

  Path            tslint > update-notifier > configstore > dot-prop             

  More info       https://npmjs.com/advisories/1213                             




                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Low             Prototype Pollution                                           

  Package         minimist                                                      

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3                                     

  Dependency of   vscode [dev]                                                  

  Path            vscode > mocha > mkdirp > minimist                            

  More info       https://npmjs.com/advisories/1179                             

found 3 vulnerabilities (2 low, 1 high) in 133 scanned packages
  2 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
~~~

**Comment by DrMerfy** [comment]
Mhm okay cool, I suggest not to add minimist as a dependency and let @vscode deal with it. As I understand it is not something really crucial. If we add it, we will have to keep track of their versioning as well and change it each time they chage.

Everything else should be good to go :D

**Comment by GitMensch** [comment]
Commit amended with the change as requested, then force-pushed, then merged.
Note: that actually finishes my todos here for now (other than the question about the possibly unnecessary check for "config really updated?").

**Pull request merged**
